ssa_seguridad_seguridad_usuarios:
    resource: "@SSASeguridadBundle/Resources/config/routing/usuarios.yml"
    prefix:   /seguridad/usuarios

ssa_seguridad_seguridad_grupos:
    resource: "@SSASeguridadBundle/Resources/config/routing/grupos.yml"
    prefix:   /seguridad/grupos

ssa_seguridad_seguridad_roles:
    resource: "@SSASeguridadBundle/Resources/config/routing/roles.yml"
    prefix:   /seguridad/roles


login:
    path:     /login
    defaults: { _controller: SSASeguridadBundle:Seguridad:login }

login_check:
    path:   /login_check
