services:
#    ssa_utilidades.example:
#        class: SSA\UtilidadesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    ssa_utilidades.base:
        class: SSA\UtilidadesBundle\Manager\BaseManager
        arguments: ["@doctrine", "@security.context", '@router']
        calls:
            - [setRequest, ['@?request=']]
            
    #Form types
    ssa_utilidades.form.type.searh_key:
        class: SSA\UtilidadesBundle\Form\Type\SearchKeyType
        tags:
            - { name: form.type, alias: search_key }
