services:
#    ssa_utilidades.example:
#        class: SSA\UtilidadesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    ssa_utilidades.base:
        class: SSA\UtilidadesBundle\Manager\BaseManager
        arguments: ["@doctrine", "@security.context", '@router', '@session']
        calls:
            - [setRequest, ['@?request=']]
            
    ssa_utilidades.dataTables:
        class: SSA\UtilidadesBundle\Manager\DataTablesManager
        arguments: ["@doctrine"]
            
    #Form types
    ssa_utilidades.form.type.searh_key:
        class: SSA\UtilidadesBundle\Form\Type\SearchKeyType
        arguments: ['@doctrine']
        tags:
            - { name: form.type, alias: search_key }
    
    ssa_utilidades.session_expiry:
        class: SSA\UtilidadesBundle\Listener\SessionExpiryListener
        arguments: ['@session', %session_max_idle_time%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
