admin_grupos:
    path:     /
    defaults: { _controller: "AppBundle:Grupos:index" }

admin_grupos_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Grupos:show" }

admin_grupos_new:
    path:     /new
    defaults: { _controller: "AppBundle:Grupos:new" }

admin_grupos_create:
    path:     /create
    defaults: { _controller: "AppBundle:Grupos:create" }
    requirements: { _method: post }

admin_grupos_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Grupos:edit" }

admin_grupos_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Grupos:update" }
    requirements: { _method: post|put }

admin_grupos_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Grupos:delete" }
    requirements: { _method: post|delete }
