admin_roles:
    path:     /
    defaults: { _controller: "AppBundle:Roles:index" }

admin_roles_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Roles:show" }

admin_roles_new:
    path:     /new
    defaults: { _controller: "AppBundle:Roles:new" }

admin_roles_create:
    path:     /create
    defaults: { _controller: "AppBundle:Roles:create" }
    requirements: { _method: post }

admin_roles_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Roles:edit" }

admin_roles_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Roles:update" }
    requirements: { _method: post|put }

admin_roles_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Roles:delete" }
    requirements: { _method: post|delete }
