admin_articulos:
    path:     /
    defaults: { _controller: "AppBundle:Admin/Articulos:index" }

admin_articulos_ajax:
    path:     /ajax
    defaults: { _controller: "AppBundle:Admin/Articulos:indexAjax" }

admin_articulos_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Admin/Articulos:show" }

admin_articulos_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin/Articulos:new" }

admin_articulos_create:
    path:     /create
    defaults: { _controller: "AppBundle:Admin/Articulos:create" }
    requirements: { _method: post }

admin_articulos_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Admin/Articulos:edit" }

admin_articulos_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Admin/Articulos:update" }
    requirements: { _method: post|put }

admin_articulos_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Admin/Articulos:delete" }
    requirements: { _method: post|delete }
