admin_entradas:
    path:     /
    defaults: { _controller: "AppBundle:Admin/Entradas:index" }

admin_entradas_ajax:
    path:     /ajax
    defaults: { _controller: "AppBundle:Admin/Entradas:indexAjax" }

admin_entradas_show:
    path:     /show
    defaults: { _controller: "AppBundle:Admin/Entradas:show" }

admin_entradas_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin/Entradas:new" }

admin_entradas_create:
    path:     /create
    defaults: { _controller: "AppBundle:Admin/Entradas:create" }
    requirements: { _method: post }

admin_entradas_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Admin/Entradas:edit" }

admin_entradas_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Admin/Entradas:update" }
    requirements: { _method: post|put }

admin_entradas_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Admin/Entradas:delete" }
    requirements: { _method: post|delete }

admin_entradas_mostrar_con_articulos:
    path:     /{id}/mostrar_con_articulos
    defaults: { _controller: "AppBundle:Admin/Entradas:mostrarConArticulos" }

admin_entradas_pdf:
    path:     /{id}/pdf
    defaults: { _controller: "AppBundle:Admin/Entradas:pdf" }
