admin_entradadetalles:
    path:     /entrada/{id}
    defaults: { _controller: "AppBundle:Admin/EntradaDetalles:index" }

admin_entradadetalles_show:
    path:     /show
    defaults: { _controller: "AppBundle:Admin/EntradaDetalles:show" }

admin_entradadetalles_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin/EntradaDetalles:new" }

admin_entradadetalles_create:
    path:     /create
    defaults: { _controller: "AppBundle:Admin/EntradaDetalles:create" }
    requirements: { _method: post }

admin_entradadetalles_edit:
    path:     /edit
    defaults: { _controller: "AppBundle:Admin/EntradaDetalles:edit" }

admin_entradadetalles_update:
    path:    /update
    defaults: { _controller: "AppBundle:Admin/EntradaDetalles:update" }
    requirements: { _method: post|put }

admin_entradadetalles_delete:
    path:     /delete
    defaults: { _controller: "AppBundle:Admin/EntradaDetalles:delete" }
    requirements: { _method: post|delete }
    
admin_entradadetalles_buscar_articulo:
    path:     /buscar_articulo
    defaults: { _controller: "AppBundle:Admin/EntradaDetalles:buscarArticulo" }
