admin_programas:
    path:     /
    defaults: { _controller: "AppBundle:Admin/Programas:index" }

admin_programas_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Admin/Programas:show" }

admin_programas_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin/Programas:new" }

admin_programas_create:
    path:     /create
    defaults: { _controller: "AppBundle:Admin/Programas:create" }
    requirements: { _method: post }

admin_programas_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Admin/Programas:edit" }

admin_programas_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Admin/Programas:update" }
    requirements: { _method: post|put }

admin_programas_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Admin/Programas:delete" }
    requirements: { _method: post|delete }
    
admin_programas_popup_buscar:
    path:     /popup_buscar
    defaults: { _controller: "AppBundle:Admin/Programas:popupBuscar" }
