admin_proveedores:
    path:     /
    defaults: { _controller: "AppBundle:Admin/Proveedores:index" }

admin_proveedores_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Admin/Proveedores:show" }

admin_proveedores_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin/Proveedores:new" }

admin_proveedores_create:
    path:     /create
    defaults: { _controller: "AppBundle:Admin/Proveedores:create" }
    requirements: { _method: post }

admin_proveedores_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Admin/Proveedores:edit" }

admin_proveedores_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Admin/Proveedores:update" }
    requirements: { _method: post|put }

admin_proveedores_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Admin/Proveedores:delete" }
    requirements: { _method: post|delete }
    
admin_proveedores_popup_buscar:
    path:     /popup_buscar
    defaults: { _controller: "AppBundle:Admin/Proveedores:popupBuscar" }
    
admin_proveedores_buscar_ajax:
    path:     /buscar_ajax
    defaults: { _controller: "AppBundle:Admin/Proveedores:buscarAjax" }
