app_admin_programas:
    resource: "@AppBundle/Resources/config/routing/Admin/programas.yml"
    prefix:   /admin/programas

app_admin_entradas:
    resource: "@AppBundle/Resources/config/routing/Admin/entradas.yml"
    prefix:   /admin/entradas

app_admin_almacenes:
    resource: "@AppBundle/Resources/config/routing/Admin/almacenes.yml"
    prefix:   /admin/almacenes
    
admin_homepage:
    path:     /admin/
    defaults: { _controller: AppBundle:Default:indexAdmin }

logout:
    path: /logout
    
app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_demo:
    path: /demo
    defaults: { _controller: AppBundle:Default:demo }
