app_admin_articulos:
    resource: "@AppBundle/Resources/config/routing/articulos.yml"
    prefix:   /admin/articulos

app_admin_entradadetalles:
    resource: "@AppBundle/Resources/config/routing/Admin/entradadetalles.yml"
    prefix:   /admin/entradadetalles

app_admin_proveedores:
    resource: "@AppBundle/Resources/config/routing/Admin/proveedores.yml"
    prefix:   /admin/proveedores

app_admin_programas:
    resource: "@AppBundle/Resources/config/routing/Admin/programas.yml"
    prefix:   /admin/programas

app_admin_entradas:
    resource: "@AppBundle/Resources/config/routing/Admin/entradas.yml"
    prefix:   /admin/entradas
    
app_admin_salidas:
    resource: "@AppBundle/Resources/config/routing/Admin/salidas.yml"
    prefix:   /admin/salidas

app_admin_salidadetalles:
    resource: "@AppBundle/Resources/config/routing/Admin/salidadetalles.yml"
    prefix:   /admin/salidadetalles

app_admin_almacenes:
    resource: "@AppBundle/Resources/config/routing/Admin/almacenes.yml"
    prefix:   /admin/almacenes
    
admin_homepage:
    path:     /admin/
    defaults: { _controller: AppBundle:Default:indexAdmin }

logout:
    path: /logout
    
app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_demo:
    path: /demo
    defaults: { _controller: AppBundle:Default:demo }
