app_admin_almacenes:
    resource: "@AppBundle/Resources/config/routing/almacenes.yml"
    prefix:   /admin/almacenes

logout:
    path: /logout
    
app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_demo:
    path: /demo
    defaults: { _controller: AppBundle:Default:demo }
