<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InventarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventarioRepository extends EntityRepository
{
}
